package core_test

import (
	"sort"
	"testing"
	"time"

	"github.com/lagz0ne/remmd/internal/core"
)

func TestNewDocument_HasAutoGeneratedID(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("My Doc", "owner-1")
	if doc.ID == "" {
		t.Fatal("expected non-empty ID")
	}
}

func TestNewDocument_UniqueIDs(t *testing.T) {
	t.Parallel()
	ids := make(map[string]bool, 100)
	for i := 0; i < 100; i++ {
		doc := core.NewDocument("doc", "owner")
		if ids[doc.ID] {
			t.Fatalf("duplicate document ID at iteration %d", i)
		}
		ids[doc.ID] = true
	}
}

func TestNewDocument_EmptySections(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("My Doc", "owner-1")
	if len(doc.Sections()) != 0 {
		t.Fatalf("expected 0 sections, got %d", len(doc.Sections()))
	}
}

func TestDocument_AddSections(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("My Doc", "owner-1")
	sections := []core.Section{
		{ID: "s1", DocID: "d1", Title: "hello", Content: "hello content"},
		{ID: "s2", DocID: "d1", Title: "world", Content: "world content"},
	}
	doc.AddSections(sections)
	if len(doc.Sections()) != 2 {
		t.Fatalf("expected 2 sections, got %d", len(doc.Sections()))
	}
}

func TestNewDocument_TitleAndOwnerID(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("My Doc", "owner-42")
	if doc.Title != "My Doc" {
		t.Errorf("Title = %q, want %q", doc.Title, "My Doc")
	}
	if doc.OwnerID != "owner-42" {
		t.Errorf("OwnerID = %q, want %q", doc.OwnerID, "owner-42")
	}
}

func TestNewDocument_CreatedAtIsSet(t *testing.T) {
	t.Parallel()
	before := time.Now()
	doc := core.NewDocument("doc", "owner")
	after := time.Now()
	if doc.CreatedAt.Before(before) || doc.CreatedAt.After(after) {
		t.Fatalf("CreatedAt %v not in [%v, %v]", doc.CreatedAt, before, after)
	}
}

func TestNewDocument_StatusIsActive(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("doc", "owner")
	if doc.Status != core.DocumentActive {
		t.Errorf("Status = %q, want %q", doc.Status, core.DocumentActive)
	}
}

func TestDocument_TagsEmptyInitially(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("doc", "owner")
	tags := doc.Tags()
	if len(tags) != 0 {
		t.Fatalf("expected 0 tags, got %d", len(tags))
	}
}

func TestDocument_AddTag(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("doc", "owner")
	doc.AddTag("important")
	tags := doc.Tags()
	if len(tags) != 1 || tags[0] != "important" {
		t.Fatalf("expected [important], got %v", tags)
	}
}

func TestDocument_AddTag_Idempotent(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("doc", "owner")
	doc.AddTag("important")
	doc.AddTag("important")
	tags := doc.Tags()
	if len(tags) != 1 {
		t.Fatalf("expected 1 tag after duplicate add, got %d", len(tags))
	}
}

func TestDocument_RemoveTag(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("doc", "owner")
	doc.AddTag("a")
	doc.AddTag("b")
	doc.RemoveTag("a")
	tags := doc.Tags()
	if len(tags) != 1 || tags[0] != "b" {
		t.Fatalf("expected [b], got %v", tags)
	}
}

func TestDocument_TagsSorted(t *testing.T) {
	t.Parallel()
	doc := core.NewDocument("doc", "owner")
	doc.AddTag("zebra")
	doc.AddTag("apple")
	doc.AddTag("mango")
	tags := doc.Tags()
	if !sort.StringsAreSorted(tags) {
		t.Fatalf("expected sorted tags, got %v", tags)
	}
}
